name: Build and Push obbyircd Docker Image

on:
  push:
    branches:
      - unreal60_dev
    tags:
      - 'v*'
    paths:
      - 'src/**'
      - 'include/**'
      - 'doc/conf/**'
      - 'extras/**'
      - 'autoconf/**'
      - 'configure*'
      - 'Config'
      - 'Makefile.in'
      - 'BSDmakefile'
      - 'obbyircd.in'
      - 'docker/**'
      - '.dockerignore'
      - '.github/workflows/docker-obbyircd.yml'
      - '.github/workflows/docker-build-push.yml'
  pull_request:
    branches:
      - unreal60_dev
    paths:
      - 'src/**'
      - 'docker/**'
      - '.github/workflows/docker-obbyircd.yml'
      - '.github/workflows/docker-build-push.yml'
  workflow_dispatch:

jobs:
  build:
    name: Build obbyircd Image
    uses: ./.github/workflows/docker-build-push.yml
    with:
      image_name: obbyircd
      context: .
      dockerfile: ./docker/Dockerfile
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
